name: rea_dream_ai
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1


environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  desktop_drop: ^0.6.1 # 用于处理桌面文件拖放
  path: ^1.8.3       # 用于方便地处理文件路径和扩展名# 用于解析 EPUB 文件的元数据和内容结构
  get_it: ^7.6.4    # 用于依赖注入和服务定位
  path_provider: any # 用于获取应用缓存目录
  archive: any       # 用于解压EPUB (zip) 文件
  xml: ^6.6.1        # 用于解析EPUB内的XML文件 (.opf, toc.ncx)
  html: ^0.15.2 # 用于解析和处理HTML内容
  uuid: any        # 用于为缓存文件夹生成唯一ID
  json_annotation: ^4.9.0 # 帮助处理JSON序列化
  file_picker: ^10.3.3 # 用于文件和目录选择器
  http: any #  用于网络请求
  tiktoken: ^1.0.3        # 用于计算token数
  pool: ^1.5.1 # 用于处理并发任务池
  web_socket_channel: ^3.0.3  # 用于ComfyUI的WebSocket通信
  dart_jsonwebtoken: ^2.11.0  # 用于Kling的JWT Token生成
  cupertino_icons: ^1.0.8 # iOS风格的图标
  url_launcher: ^6.1.14 # 用于打开外部链接
  video_player: ^2.8.6  # 用于视频播放
  video_player_win: ^3.2.0
  collection: ^1.18.0 # 提供额外的集合类和实用工具
  intl: ^0.18.1         # 用于格式化日期和时间
  image: ^4.5.4       # 用于图像处理和转换
  window_manager: ^0.5.1 # 用于管理桌面窗口
  screen_retriever: ^0.2.0 # 用于获取屏幕信息

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # 开发依赖
  build_runner: ^2.8.0  # 配合 json_serializable 使用
  json_serializable: ^6.7.1 # 用于生成 JSON 序列化代码
  rename: ^3.1.0

flutter:
  uses-material-design: true

  # 声明资源文件
  assets:
    # 这样会包含 assets/comfyui/ 文件夹下的所有文件
    - assets/comfyui/

  # 添加字体声明
  fonts:
    - family: NotoSansSC  # 这是你给字体起的名字，在代码中会用到
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        # 如果你有不同字重的字体文件，可以继续在这里添加
        # - asset: assets/fonts/NotoSansSC-Bold.ttf
        #   weight: 700