# 工作流的名称
name: Build and Deploy Pre-release

# 触发工作流的事件
on:
  push:
    # 只有当推送到 main 分支时才触发
    branches:
      - main

# 定义工作流中的任务
jobs:
  build-and-release:
    # 任务的名称
    name: Build and Release Pre-release
    # 指定运行此任务的虚拟机环境
    runs-on: windows-latest

    # 为整个 job 设置环境变量，简化后续步骤
    env:
      PROJECT_NAME: AiMoee # <--- 简化点：直接在此处定义你的项目名

    # 任务的执行步骤
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 步骤3：安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 步骤4：构建 Windows release 版本的应用
      - name: Build Windows executable
        run: flutter build windows --release

      # 步骤5：生成唯一的发布标签
      - name: Generate release tag
        id: generate_tag # id 依然有用，虽然我们主要用 GITHUB_ENV
        shell: pwsh
        run: |
          # 生成一个基于 日期-时间-SHA 的唯一标签名
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $tagName = "nightly-$date-$shortSha"
          echo "TAG_NAME=$tagName" >> $env:GITHUB_ENV
          
          echo "Generated tag name: $tagName"
          echo "Project name: ${{ env.PROJECT_NAME }}"

      # 步骤6：将构建产物打包成 ZIP (已修复)
      - name: Package release assets
        shell: pwsh # 明确指定 shell
        run: |
          # 构造最终的 ZIP 文件名
          $zipFileName = "${{ env.PROJECT_NAME }}-${{ env.TAG_NAME }}-windows.zip"
          echo "ZIP_FILE_NAME=$zipFileName" >> $env:GITHUB_ENV # 将文件名存入环境变量，方便下一步引用
          
          # 使用更稳健的方式进行压缩
          Get-ChildItem -Path build\windows\runner\Release | Compress-Archive -DestinationPath $zipFileName
          
          echo "Successfully created $zipFileName"

      # 步骤7：创建 GitHub Pre-release 并上传 ZIP 包
      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          # 标记为预发布版本
          prerelease: true
          # 我们在前面步骤中动态生成的唯一标签名
          tag_name: ${{ env.TAG_NAME }}
          # Release 的标题
          name: Pre-release ${{ env.TAG_NAME }}
          # 自动生成此版本与上一个版本之间的变更日志
          generate_release_notes: true
          # 指向我们要上传的文件路径 (引用上一步生成的文件名)
          files: ${{ env.ZIP_FILE_NAME }}
          # GitHub Actions 自动提供的 token
          token: ${{ secrets.GITHUB_TOKEN }}