name: Build and Deploy Pre-release

on:
  push:
    # 只有当推送到 main 分支时才触发
    branches:
      - main # 如果你的主分支是 master，请修改为 master

jobs:
  build-and-release:
    # 任务的名称
    name: Build and Release Pre-release
    # 指定运行此任务的虚拟机环境
    runs-on: windows-latest

    # 任务的执行步骤
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 步骤3：安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 步骤4：构建 Windows release 版本的应用
      - name: Build Windows executable
        run: flutter build windows --release

      # 步骤5：准备发布所需的信息
      - name: Prepare release info
        id: prepare_info
        shell: pwsh
        run: |
          echo "PROJECT_NAME=AiMoee" >> $env:GITHUB_ENV
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $tagName = "nightly-$date-$shortSha"
          echo "TAG_NAME=$tagName" >> $env:GITHUB_ENV
          
          echo "Generated tag name: $tagName"
          echo "Project name: AiMoee"

      # 步骤6：调试构建目录（已修正路径）
      - name: Debug build directory
        shell: pwsh
        run: |
          Write-Output "Current directory: $(Get-Location)"
          $releasePath = 'build\windows\x64\runner\Release' # <-- 修正路径变量
          Write-Output "Checking for release directory: $releasePath"
          Write-Output "Release directory exists: $(Test-Path $releasePath)"
          if (Test-Path $releasePath) {
            Write-Output "Contents of Release directory:"
            Get-ChildItem $releasePath | ForEach-Object { Write-Output "  - $($_.Name)" }
          } else {
            Write-Output "Release directory not found. Full build structure:"
            Get-ChildItem 'build' -Recurse | ForEach-Object { Write-Output "  - $($_.FullName)" }
          }

      # 步骤7：将构建产物打包成 ZIP（已修正路径）
      - name: Package release assets
        shell: pwsh
        run: |
          # 使用正确的构建输出路径
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath "Aimoee-windows.zip" -Force

      # 步骤8：创建 GitHub Pre-release 并上传 ZIP 包（已修正 tag_name）
      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          # 标记为预发布版本
          prerelease: true
          # 使用我们之前动态生成的唯一标签名
          tag_name: ${{ env.TAG_NAME }}
          # Release 的标题
          name: 测试版-自动同步源码
          # 自动生成此版本与上一个版本之间的变更日志
          generate_release_notes: true
          # 指向我们要上传的文件路径
          files: Aimoee-windows.zip
          # GitHub Actions 自动提供的 token
          token: ${{ secrets.GITHUB_TOKEN }}