name: Build and Deploy Pre-release

on:
  workflow_dispatch: # 允许你从 Actions 选项卡手动运行此工作流
  push:
    # 只有当推送到 main 分支时才触发
    branches:
      - main # 如果你的主分支是 master，请修改为 master

# 授予写入仓库内容的权限，以便创建和删除 Release
permissions:
  contents: write

jobs:
  build-and-release:
    # 任务的名称
    name: Build and Release Pre-release
    # 指定运行此任务的虚拟机环境
    runs-on: windows-latest

    # 任务的执行步骤
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 步骤3：安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 步骤4：构建 Windows release 版本的应用
      - name: Build Windows executable
        run: flutter build windows --release

      # 步骤5：将构建产物打包成 ZIP
      - name: Package release assets
        shell: pwsh
        run: |
          # 使用正确的构建输出路径
          Compress-Archive -Path build\windows\x64\runner\Release\* -DestinationPath "ReaDreamAI-beta-windows.zip" -Force

      # 步骤6：删除旧的预览版
      - name: Delete old pre-releases
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: Beta
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
          
      # 步骤7：创建 GitHub Pre-release 并上传 ZIP 包
      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: Beta
          name: ReaDreamAI 开发测试版本，由最新源码自动打包 
          draft: false
          prerelease: true
          generate_release_notes: true 
          files: ReaDreamAI-beta-windows.zip
          token: ${{ secrets.GITHUB_TOKEN }}