name: Build and Deploy Pre-release

on:
  push:
    # 只有当推送到 main 分支时才触发
    branches:
      - main # 如果你的主分支是 master，请修改为 master

jobs:
  build-and-release:
    # 任务的名称
    name: Build and Release Pre-release
    # 指定运行此任务的虚拟机环境
    runs-on: windows-latest

    # 任务的执行步骤
    steps:
      # 步骤1：检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 步骤2：设置 Flutter 环境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 步骤3：安装项目依赖
      - name: Install dependencies
        run: flutter pub get

      # 步骤4：构建 Windows release 版本的应用
      - name: Build Windows executable
        run: flutter build windows --release

      # 步骤5：准备发布所需的信息（简化：直接硬编码项目名，避免从 pubspec.yaml 动态读取）
      - name: Prepare release info
        id: prepare_info
        shell: pwsh # 明确使用 PowerShell Core
        run: |
          # 直接设置项目名为 AiMoee（简化动态参数）
          echo "PROJECT_NAME=AiMoee" >> $env:GITHUB_ENV

          # 生成一个基于 日期-时间-SHA 的唯一标签名
          $date = Get-Date -Format "yyyyMMdd-HHmmss"
          $shortSha = "${{ github.sha }}".Substring(0, 7)
          $tagName = "nightly-$date-$shortSha"
          echo "TAG_NAME=$tagName" >> $env:GITHUB_ENV
          
          echo "Generated tag name: $tagName"
          echo "Project name: AiMoee"

      # 步骤6：调试构建目录（新增：验证 Release 目录是否存在及其内容）
      - name: Debug build directory
        shell: pwsh
        run: |
          Write-Output "Current directory: $(Get-Location)"
          Write-Output "Build directory exists: $(Test-Path 'build')"
          Write-Output "Windows runner directory exists: $(Test-Path 'build\windows\runner')"
          Write-Output "Release directory exists: $(Test-Path 'build\windows\runner\Release')"
          if (Test-Path 'build\windows\runner\Release') {
            Write-Output "Contents of Release directory:"
            Get-ChildItem 'build\windows\runner\Release' | ForEach-Object { Write-Output "  - $($_.Name)" }
          } else {
            Write-Output "Release directory not found. Full build structure:"
            Get-ChildItem 'build' -Recurse | ForEach-Object { Write-Output "  - $($_.FullName)" }
          }

      # 步骤7：将构建产物打包成 ZIP（修复路径：移除引号以允许通配符展开，并确保路径正确）
      - name: Package release assets
        shell: pwsh
        run: |
          # 使用不带引号的路径以展开 * 通配符
          Compress-Archive -Path build\windows\runner\Release\* -DestinationPath "Aimoee-windows.zip" -Force

      # 步骤8：创建 GitHub Pre-release 并上传 ZIP 包
      # 注意：这个 Action 会自动为我们创建 Git 标签
      - name: Create GitHub Pre-release
        uses: softprops/action-gh-release@v2
        with:
          # 标记为预发布版本
          prerelease: true
          # 我们在前面步骤中动态生成的唯一标签名
          tag_name: bete
          # Release 的标题
          name: 测试版-自动同步源码
          # 自动生成此版本与上一个版本之间的变更日志
          generate_release_notes: true
          # 指向我们要上传的文件路径
          files: Aimoee-windows.zip
          # GitHub Actions 自动提供的 token
          token: ${{ secrets.GITHUB_TOKEN }}